[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyproresult"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "lxml>=6.0.2",
]

[dependency-groups]
dev = [
    "setuptools",
    "wheel",
    "ruff",
]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
